# Generated by Django 4.1.4 on 2023-01-21 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import test_cloud.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_cloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(upload_to=test_cloud.utils.file_edit_name),
        ),
    ]
